# Generated by Django 4.2.6 on 2023-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Django', 'Django'), ('Python', 'Python'), ('Django_rest_framework', 'Django Rest Framework'), ('Java', 'Java'), ('JavaScript', 'Javascript'), ('PHP', 'Php'), ('Postgres', 'Postgres'), ('MySql', 'Mysql'), ('AWS', 'Aws')], default='NONE', max_length=50),
        ),
    ]
