# Generated by Django 4.2.6 on 2023-10-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
    ]
