# Generated by Django 4.2.6 on 2023-10-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_downvote_upvote_delete_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='downVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='upVotes',
            field=models.IntegerField(default=0),
        ),
    ]
